apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-server
  template:
    metadata:
      labels:
        app: config-server
    spec:
      containers:
      - name: config-server
        image: anishkini07/spring-petclinic-config-server:latest
        ports:
        - containerPort: 8888
        env:
        - name: SPRING_CLOUD_CONFIG_URI
          value: http://config-server:8888/
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          value: http://discovery-server:8761/eureka/
---
apiVersion: v1
kind: Service
metadata:
  name: config-server
spec:
  selector:
    app: config-server
  ports:
  - protocol: TCP
    port: 8888
    targetPort: 8888
