apiVersion: v1
kind: Service
metadata:
  name: prometheus
  labels:
    app: prometheus
spec:
  type: ClusterIP
  ports:
    - port: 9090
      targetPort: 9090
  selector:
    app: prometheus
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus:latest
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: prometheus-config
              mountPath: /etc/prometheus/
      volumes:
        - name: prometheus-config
          configMap:
            name: prometheus-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  labels:
    app: prometheus
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'api-gateway'
        metrics_path: /actuator/prometheus
        static_configs:
          - targets: ['api-gateway:8080']
        relabel_configs:
          - source_labels: [__address__]
            target_label: application
            replacement: petclinic

      - job_name: 'customers-service'
        metrics_path: /actuator/prometheus
        static_configs:
          - targets: ['customers-service:8081']
        relabel_configs:
          - source_labels: [__address__]
            target_label: application
            replacement: petclinic

      - job_name: 'vets-service'
        metrics_path: /actuator/prometheus
        static_configs:
          - targets: ['vets-service:8083']
        relabel_configs:
          - source_labels: [__address__]
            target_label: application
            replacement: petclinic

      - job_name: 'visits-service'
        metrics_path: /actuator/prometheus
        static_configs:
          - targets: ['visits-service:8082']
        relabel_configs:
          - source_labels: [__address__]
            target_label: application
            replacement: petclinic
