apiVersion: apps/v1
kind: Deployment
metadata:
  name: vets-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vets-service
  template:
    metadata:
      labels:
        app: vets-service
    spec:
      containers:
      - name: vets-service
        image: anishkini07/spring-petclinic-vets-service:latest
        ports:
        - containerPort: 8083
        env:
        - name: SPRING_CONFIG_IMPORT
          value: configserver:http://config-server:8888/
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          value: http://discovery-server:8761/eureka/
        - name: SERVER_PORT
          value: "8083"
        - name: EUREKA_INSTANCE_NONSECUREPORT
          value: "8083"
        - name: EUREKA_INSTANCE_NONSECUREPORT_ENABLED
          value: "true"
        - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
          value: "true"
        args:
        - --eureka.client.service-url.defaultZone=http://discovery-server:8761/eureka/
---
apiVersion: v1
kind: Service
metadata:
  name: vets-service
spec:
  selector:
    app: vets-service
  ports:
  - protocol: TCP
    port: 8083
    targetPort: 8083
